// Metadata tiếng Việt cho các chỉ số vĩ mô Mỹ.
// byFredId: lookup chính xác theo FRED series ID.
// byNamePattern: regex match tên chỉ số (cho releases từ investing.com).

window.INDICATORS = {
  byFredId: {
    // ===== LẠM PHÁT =====
    "CPIAUCSL": {
      name: "CPI — Chỉ số giá tiêu dùng (tất cả mặt hàng)",
      unit: "Index 1982-84=100",
      freq: "Hàng tháng",
      source: "BLS (Cục Thống kê Lao động Mỹ)",
      what: "Đo mức giá trung bình của một rổ hàng hóa và dịch vụ mà hộ gia đình Mỹ tiêu thụ. Bao gồm thực phẩm, năng lượng, nhà ở, y tế, giao thông, giáo dục…",
      high_means: "Lạm phát tăng. Fed sẽ có xu hướng hawkish (giữ/tăng lãi suất). USD↑, yields↑, equities (đặc biệt tech/growth) chịu áp lực do DCF discount tăng.",
      low_means: "Lạm phát giảm/giảm tốc. Fed có không gian cắt lãi suất → dovish. Tốt cho equities, đặc biệt tech, REITs, utilities.",
      why: "Là chỉ số lạm phát được theo dõi rộng rãi nhất. Quyết định trực tiếp đến chính sách tiền tệ của Fed. CPI cao kéo dài → Fed buộc phải tăng lãi suất → khủng hoảng tiềm tàng.",
      watch: "So sánh YoY (cùng kỳ năm trước) và MoM (tháng-trên-tháng). Mục tiêu Fed: 2% lạm phát. Trên 3% là vùng cảnh báo.",
    },
    "CPILFESL": {
      name: "Core CPI — CPI lõi (loại trừ thực phẩm & năng lượng)",
      unit: "Index 1982-84=100",
      freq: "Hàng tháng",
      source: "BLS",
      what: "CPI sau khi loại bỏ thực phẩm và năng lượng — 2 nhóm biến động mạnh do thời tiết/dầu mỏ. Phản ánh áp lực giá dai dẳng (sticky).",
      high_means: "Lạm phát lõi cao = áp lực giá lan toả → Fed lo ngại lạm phát ăn sâu vào kỳ vọng. Hawkish hơn.",
      low_means: "Lạm phát lõi hạ → tín hiệu disinflation thực sự. Fed dễ pivot sang dovish.",
      why: "Fed quan tâm Core CPI HƠN headline CPI khi ra quyết định, vì nó loại nhiễu. Nếu headline thấp nhưng core cao → vẫn hawkish.",
      watch: "Mục tiêu: dưới 2.5% YoY. Đặc biệt theo dõi sub-component 'shelter' (nhà ở) — chiếm ~40% core CPI.",
    },
    "PCEPI": {
      name: "PCE — Chỉ số giá chi tiêu cá nhân",
      unit: "Index 2017=100",
      freq: "Hàng tháng",
      source: "BEA (Cục Phân tích Kinh tế)",
      what: "Đo lạm phát dựa trên chi tiêu thực tế của hộ gia đình (khác CPI dùng rổ cố định). Bao quát hơn, có điều chỉnh hành vi thay thế khi giá đổi.",
      high_means: "Tương tự CPI — Fed hawkish.",
      low_means: "Tương tự CPI — Fed dovish.",
      why: "Đây là **chỉ số lạm phát ưa thích của Fed**. Khi báo cáo FOMC nhắc mục tiêu 2% lạm phát, họ nói về PCE chứ không phải CPI.",
      watch: "Thường thấp hơn CPI 0.3-0.5 điểm phần trăm. PCE > 2% → Fed vẫn cảnh giác.",
    },
    "PCEPILFE": {
      name: "Core PCE — PCE lõi",
      unit: "Index 2017=100",
      freq: "Hàng tháng",
      source: "BEA",
      what: "PCE loại bỏ thực phẩm và năng lượng. **Là chỉ số quan trọng NHẤT** mà Fed dùng để định nghĩa 'mục tiêu lạm phát 2%'.",
      high_means: "Fed lo ngại nhất khi Core PCE cao kéo dài. Hawkish stance gần như chắc chắn.",
      low_means: "Core PCE hạ về 2% = tín hiệu Fed có thể cắt lãi suất.",
      why: "Toàn bộ chính sách tiền tệ Mỹ xoay quanh việc Core PCE có quay về 2% hay không. Mỗi 0.1 điểm phần trăm thay đổi đều ảnh hưởng lớn đến thị trường.",
      watch: "3-month annualized rate (tốc độ 3 tháng quy năm) là thước đo Fed dùng để đánh giá xu hướng gần. Trên 3% → còn xa mục tiêu.",
    },
    "PPIFID": {
      name: "PPI — Chỉ số giá sản xuất (Final Demand)",
      unit: "Index Nov 2009=100 · đọc theo YoY%",
      freq: "Hàng tháng",
      source: "BLS",
      what: "Đo giá đầu ra của nhà sản xuất ở mức 'final demand' (cùng rổ mà investing.com/thị trường quote). Đo lạm phát ở giai đoạn TRƯỚC khi đến tay người tiêu dùng.",
      high_means: "Áp lực giá đầu vào tăng → có thể truyền vào CPI tháng sau. Cảnh báo sớm về lạm phát.",
      low_means: "Áp lực giá đầu vào giảm → CPI có thể hạ. Tốt cho margin của doanh nghiệp.",
      why: "Là **leading indicator** cho CPI. Nếu PPI tăng mạnh nhưng CPI chưa → công ty đang 'gánh' chi phí, sớm muộn sẽ chuyển sang người tiêu dùng hoặc margin sẽ co. (Lưu ý: đây là Final Demand — KHÔNG phải PPI All Commodities/PPIACO, vốn cho YoY cao hơn nhiều.)",
      watch: "PPI tăng nhanh + Retail Sales yếu = squeeze biên lợi nhuận doanh nghiệp → equities xấu.",
    },
    "PPIFES": {
      name: "Core PPI — PPI Final Demand ex Food & Energy",
      unit: "Index Apr 2010=100 · đọc theo YoY%",
      freq: "Hàng tháng (cùng ngày PPI headline)",
      source: "BLS",
      what: "PPI Final Demand loại trừ thực phẩm & năng lượng — phản ánh áp lực giá đầu vào cốt lõi, ít nhiễu hơn headline.",
      high_means: "Áp lực giá lõi dai dẳng → risk lạm phát sticky, xấu cho Growth/Tech.",
      low_means: "Giá lõi hạ nhiệt → tốt cho margin và equities nói chung.",
      why: "Cross-check với Core CPI/Core PCE. Fed quan tâm phần lõi vì nó dự báo xu hướng tốt hơn.",
      watch: "Đọc YoY%. Phân kỳ giữa Core PPI và Core CPI = tín hiệu về margin doanh nghiệp.",
    },

    // ===== LAO ĐỘNG =====
    "PAYEMS": {
      name: "Nonfarm Payrolls (NFP) — Việc làm phi nông nghiệp",
      unit: "Nghìn người (cộng dồn)",
      freq: "Hàng tháng (thứ Sáu đầu tháng)",
      source: "BLS",
      what: "Tổng số người được trả lương bởi doanh nghiệp Mỹ (không tính nông trại, người tự kinh doanh, công chức liên bang). Đo trực tiếp 'sức khoẻ' thị trường lao động.",
      high_means: "Lao động mạnh → kinh tế tăng trưởng → tốt cho equities, đặc biệt Consumer Discretionary, Industrials, Financials. NHƯNG nếu quá nóng → Fed lo lương kéo lạm phát → hawkish.",
      low_means: "Lao động yếu → suy thoái risk. Fed dovish. Tốt cho Bonds, Utilities, Staples (defensive). Xấu cho cyclicals.",
      why: "Là báo cáo macro **được trade nhiều nhất**. Surprise lớn (>50k vs forecast) thường tạo ra biến động lớn ở USD/yields/equities trong vài giờ.",
      watch: "200k+/tháng = mạnh; 100-200k = trung bình; <100k = yếu; âm = suy thoái. Đi kèm Unemployment Rate, Avg Hourly Earnings.",
    },
    "UNRATE": {
      name: "Unemployment Rate — Tỷ lệ thất nghiệp",
      unit: "% lực lượng lao động",
      freq: "Hàng tháng",
      source: "BLS",
      what: "Tỷ lệ người trong lực lượng lao động đang tích cực tìm việc nhưng chưa có việc.",
      high_means: "Lao động xấu → có thể trigger 'Sahm rule' (suy thoái khi UNRATE 3M MA cao hơn 0.5% so với 12M low). Fed dovish. Equities tiêu cực ngắn hạn.",
      low_means: "Full employment → kinh tế khoẻ. Nhưng quá thấp + lương tăng = lạm phát risk → Fed hawkish.",
      why: "Cùng với NFP, là 2 nửa của 'mandate kép' của Fed (tối đa hoá việc làm + ổn định giá).",
      watch: "Vùng 'sweet spot' là 3.5-4.5%. Trên 5% = lo. Dưới 3.5% = quá nóng. **Sahm Rule** là cảnh báo recession nhạy bén.",
    },
    "ICSA": {
      name: "Initial Jobless Claims — Số đơn xin trợ cấp thất nghiệp lần đầu",
      unit: "Nghìn đơn/tuần",
      freq: "Hàng tuần (thứ Năm)",
      source: "Bộ Lao động Mỹ",
      what: "Số người mới nộp đơn xin trợ cấp thất nghiệp lần đầu trong tuần. Đo thực tế việc layoff.",
      high_means: "Layoff đang tăng → labor xấu đi → Fed dovish, recession risk. Tốt cho Bonds, Utilities. Xấu cho equities.",
      low_means: "Ít layoff → labor vẫn vững → Fed có không gian hawkish.",
      why: "Là **chỉ số tần suất cao nhất** về labor (hàng tuần thay vì hàng tháng). Trader dùng để đoán trước NFP.",
      watch: "Dưới 250k = labor strong; 250-350k = bình thường; trên 400k = yếu; trên 500k = recession signal. 4-week moving average ổn định hơn data tuần.",
    },
    "CES0500000003": {
      name: "Average Hourly Earnings (AHE) — Lương trung bình/giờ",
      unit: "USD/giờ",
      freq: "Hàng tháng (kèm NFP)",
      source: "BLS",
      what: "Lương theo giờ trung bình của công nhân khu vực tư nhân.",
      high_means: "Wage growth mạnh → áp lực lương kéo lạm phát (wage-price spiral) → Fed hawkish. Xấu cho margin công ty.",
      low_means: "Wage growth chậm → áp lực lạm phát hạ → Fed dovish.",
      why: "Fed theo dõi AHE để đánh giá liệu lạm phát có phải do labor cost đẩy lên. Nếu wage growth > productivity → margin squeeze → lạm phát kéo dài.",
      watch: "YoY 3.5-4% là vùng dễ chịu cho Fed. Trên 4.5% = cảnh báo. Dưới 3% = labor đang yếu.",
    },
    "JTSJOL": {
      name: "JOLTS — Số việc làm đang tuyển",
      unit: "Nghìn vị trí",
      freq: "Hàng tháng",
      source: "BLS",
      what: "Tổng số vị trí trống mà doanh nghiệp đang tuyển. Đo 'cầu' lao động.",
      high_means: "Doanh nghiệp đang tuyển mạnh → labor tight → áp lực lương → Fed hawkish.",
      low_means: "Cầu lao động giảm → labor cooling → tốt cho Fed dovish narrative.",
      why: "Tỷ lệ JOLTS/Unemployed (số việc trên số người thất nghiệp) là thước đo độ chặt của thị trường lao động. 1.5+ = rất chặt, <1.0 = lỏng.",
      watch: "JOLTS giảm mạnh 3 tháng liên tiếp = labor đang nguội nhanh → Fed sắp pivot.",
    },

    // ===== TĂNG TRƯỞNG =====
    "A191RL1Q225SBEA": {
      name: "Real GDP Growth — Tăng trưởng GDP thực (QoQ annualized)",
      unit: "% (QoQ đã quy năm) — giống con số investing.com quote",
      freq: "Hàng quý (3 lần công bố: advance, second, final)",
      source: "BEA",
      what: "Tốc độ tăng trưởng GDP thực so với quý trước, đã quy năm (annualized) — đây là con số headline mà thị trường/investing.com theo dõi, KHÔNG phải mức GDP tuyệt đối ($B).",
      high_means: "Kinh tế mạnh → tốt cho cyclicals (Industrials, Financials, Discretionary, Materials). Nhưng quá nóng → Fed lo lạm phát.",
      low_means: "Kinh tế yếu/recession → Fed dovish, defensive sectors (Staples, Healthcare, Utilities) outperform.",
      why: "Là **thước đo định nghĩa** của recession (theo NBER): 2 quý liên tiếp GDP âm. Quyết định 'risk-on' vs 'risk-off' regime.",
      watch: "Trend Mỹ ~2%. Trên 3% = strong; 1-2% = mềm; âm = suy thoái. Component breakdown: Consumer + Investment + Government + Net Exports.",
    },
    "RSAFS": {
      name: "Retail Sales — Doanh số bán lẻ",
      unit: "Tỷ USD",
      freq: "Hàng tháng",
      source: "Census Bureau",
      what: "Tổng doanh thu các nhà bán lẻ và dịch vụ ăn uống. Đo trực tiếp chi tiêu tiêu dùng.",
      high_means: "Consumer khoẻ → Discretionary, Communications, Materials hưởng lợi. Nhưng nếu kèm lạm phát cao → có thể chỉ là nominal growth (giá tăng chứ không phải khối lượng).",
      low_means: "Consumer yếu → Discretionary chịu áp lực, Staples defensive hơn.",
      why: "Tiêu dùng chiếm ~70% GDP Mỹ. Retail Sales là leading indicator cho GDP tiếp theo.",
      watch: "**Control group** (loại trừ ô tô, xăng, vật liệu xây dựng, nhà hàng) là phần đi vào GDP — quan trọng nhất.",
    },
    "INDPRO": {
      name: "Industrial Production — Sản xuất công nghiệp",
      unit: "Index 2017=100",
      freq: "Hàng tháng",
      source: "Federal Reserve",
      what: "Đo sản lượng của các nhà máy, mỏ, và tiện ích công cộng (điện, gas).",
      high_means: "Sản xuất mạnh → Industrials, Materials, Energy hưởng lợi.",
      low_means: "Sản xuất yếu → có thể signal recession. Cyclicals chịu áp lực.",
      why: "Là leading indicator cho recession. Manufacturing chiếm ~12% GDP nhưng có tác động lan toả mạnh.",
      watch: "Sub-component 'Manufacturing' quan trọng nhất. So với ISM Mfg PMI để cross-check.",
    },
    "MANEMP": {
      name: "Manufacturing Employment — Việc làm ngành sản xuất",
      unit: "Nghìn người",
      freq: "Hàng tháng",
      source: "BLS",
      what: "Số người làm trong ngành sản xuất (manufacturing) tại Mỹ.",
      high_means: "Sản xuất đang mở rộng — tốt cho Industrials, Materials.",
      low_means: "Sản xuất co lại — cảnh báo cho cyclicals.",
      why: "Proxy cho ISM Manufacturing PMI (ISM PMI bị paywall, không có trên FRED). Khi manuf employment giảm 3 tháng liên tiếp = recession signal.",
      watch: "So sánh với INDPRO. Nếu employment giảm nhưng output ổn = automation/productivity tăng; cả 2 giảm = stress thực sự.",
    },
    "BSCICP03USM665S": {
      name: "Business Confidence (OECD) — Niềm tin doanh nghiệp Mỹ",
      unit: "Index, 100 = trung bình dài hạn",
      freq: "Hàng tháng (có lag 1-2 tháng)",
      source: "OECD",
      what: "Khảo sát các nhà quản lý doanh nghiệp về triển vọng kinh tế: orders, inventories, employment, prices.",
      high_means: "Doanh nghiệp lạc quan → tăng capex, tuyển người → tốt cho Industrials, Tech.",
      low_means: "Doanh nghiệp bi quan → cắt giảm → leading indicator cho recession.",
      why: "Tâm lý ảnh hưởng quyết định đầu tư. Confidence sụp đổ thường đi TRƯỚC recession 3-6 tháng.",
      watch: "Lưu ý: FRED data có lag 1-2 tháng so với release thực. Có thể stale.",
    },

    // ===== NIỀM TIN =====
    "UMCSENT": {
      name: "Michigan Consumer Sentiment — Tâm lý người tiêu dùng",
      unit: "Index, 1966=100",
      freq: "2 lần/tháng (preliminary + final)",
      source: "University of Michigan",
      what: "Khảo sát 500 hộ gia đình Mỹ về niềm tin hiện tại và kỳ vọng tương lai về tài chính cá nhân, kinh doanh, mua sắm.",
      high_means: "Người tiêu dùng lạc quan → chi tiêu nhiều → tốt cho Discretionary, Retail.",
      low_means: "Bi quan → tiết kiệm, hoãn chi tiêu → xấu cho Discretionary, Auto, Housing.",
      why: "Tiêu dùng = 70% GDP, nên tâm lý tiêu dùng có tính dự báo. Cũng đo 'inflation expectations 1Y/5Y' — Fed theo dõi để xem kỳ vọng lạm phát có 'anchored' không.",
      watch: "Dưới 70 = vùng recession history. Inflation expectations 1Y > 4% = Fed lo ngại.",
    },
    "CSCICP03USM665S": {
      name: "Consumer Confidence (OECD) — Niềm tin tiêu dùng (OECD)",
      unit: "Index, 100 = trung bình dài hạn",
      freq: "Hàng tháng (có lag)",
      source: "OECD",
      what: "Khác Michigan, OECD tổng hợp khảo sát tiêu dùng theo phương pháp chuẩn quốc tế.",
      high_means: "Tiêu dùng tích cực → cyclicals tốt.",
      low_means: "Tiêu dùng yếu → defensive outperform.",
      why: "Cross-check với Michigan và Conference Board Consumer Confidence. Lưu ý có lag 1-2 tháng.",
      watch: "Phù hợp đo trend chậm, không nên dùng cho tín hiệu ngắn hạn.",
    },

    // ===== GIÁ XUẤT NHẬP KHẨU =====
    "IR": {
      name: "Import Price Index — Chỉ số giá nhập khẩu",
      unit: "Index 2000=100 (thường đọc YoY/MoM %)",
      freq: "Hàng tháng",
      source: "BLS (Cục Thống kê Lao động Mỹ)",
      what: "Giá hàng hóa Mỹ nhập khẩu (theo End Use). Kênh 'imported inflation' truyền vào CPI/PPI tháng sau.",
      high_means: "Giá nhập tăng → áp lực lạm phát nhập khẩu, đẩy chi phí đầu vào. Hawkish cho Fed; áp lực margin XLY/XLP/XLI, hưởng lợi tương đối XLE.",
      low_means: "Giá nhập giảm → disinflation phía đầu vào, dễ thở cho margin doanh nghiệp và Fed dovish hơn.",
      why: "Đi trước CPI/PPI một phần; nhạy với USD (USD mạnh → giá nhập rẻ hơn) và giá dầu/nông sản toàn cầu.",
      watch: "Tách Fuel vs Nonfuel: nonfuel import prices tăng bền mới đáng lo cho lạm phát lõi. Đối chiếu DXY và WTI.",
    },
    "IQ": {
      name: "Export Price Index — Chỉ số giá xuất khẩu",
      unit: "Index 2000=100 (thường đọc YoY/MoM %)",
      freq: "Hàng tháng",
      source: "BLS (Cục Thống kê Lao động Mỹ)",
      what: "Giá hàng hóa Mỹ xuất khẩu (theo End Use), gồm Agricultural vs Nonagricultural.",
      high_means: "Giá xuất tăng → terms-of-trade cải thiện, tốt cho nhà xuất khẩu Mỹ (XLB Materials, nông nghiệp, XLE). Có thể phản ánh cầu toàn cầu mạnh.",
      low_means: "Giá xuất giảm → biên xuất khẩu hẹp, có thể báo hiệu cầu toàn cầu yếu hoặc USD mạnh gây bất lợi cạnh tranh.",
      why: "Cùng với import prices tạo bức tranh terms-of-trade; agricultural exports rất nhạy với chu kỳ hàng hóa nông sản.",
      watch: "So sánh Agricultural vs Nonagricultural exports; USD mạnh thường kéo giá xuất (tính bằng USD) chịu áp lực.",
    },
    // ===== WATCHLIST THÊM (lao động / tăng trưởng / nhà ở) =====
    "CCSA": { name: "Continuing Jobless Claims — Số tiếp tục nhận trợ cấp", unit: "Người", freq: "Hàng tuần", source: "DOL",
      what: "Số người vẫn đang nhận trợ cấp thất nghiệp (tuần thứ 2+). Bổ sung Initial Claims.",
      high_means: "Tăng → người mất việc khó tìm việc mới → lao động yếu đi. Risk-off, ưu defensive.",
      low_means: "Thấp/giảm → tái tuyển dụng nhanh → lao động khỏe, tốt cho cyclicals.",
      watch: "Xu hướng quan trọng hơn 1 tuần; tăng bền = cảnh báo suy yếu." },
    "AWHAETP": { name: "Average Weekly Hours — Giờ làm TB tuần", unit: "Giờ", freq: "Hàng tháng", source: "BLS",
      what: "Số giờ làm bình quân khu vực tư. Leading: DN cắt giờ trước khi cắt người.",
      high_means: "Giờ làm tăng → cầu lao động mạnh → tổng lương & chi tiêu khỏe.",
      low_means: "Giảm → DN thu hẹp → cảnh báo sớm yếu lao động.",
      watch: "Giảm dưới ~34 = tín hiệu yếu." },
    "OPHNFB": { name: "Nonfarm Productivity — Năng suất lao động", unit: "%QoQ ann.", freq: "Hàng quý", source: "BLS",
      what: "Sản lượng/giờ lao động. Năng suất cao = tăng trưởng không lạm phát.",
      high_means: "Tăng → làm nhiều hơn với cùng lao động → biên lợi nhuận tốt, kìm lạm phát. Tích cực rộng.",
      low_means: "Giảm → chi phí đơn vị tăng → áp lực lạm phát/biên lợi nhuận.",
      watch: "Đi nghịch với Unit Labor Cost." },
    "ULCNFB": { name: "Unit Labor Costs — Chi phí lao động đơn vị", unit: "%QoQ ann.", freq: "Hàng quý", source: "BLS",
      what: "Chi phí lao động để tạo 1 đơn vị sản lượng. Thước đo lạm phát từ lương.",
      high_means: "Tăng mạnh → lạm phát do lương → hawkish Fed, áp lực biên lợi nhuận.",
      low_means: "Thấp → lương không gây lạm phát → dovish-friendly.",
      watch: "Fed theo dõi sát; >3-4% YoY = lo ngại." },
    "AMTMNO": { name: "Factory Orders — Đơn đặt hàng nhà máy", unit: "%MoM", freq: "Hàng tháng", source: "Census",
      what: "Tổng đơn hàng mới ngành sản xuất (durable + nondurable).",
      high_means: "Tăng → cầu công nghiệp mạnh → tốt XLI Industrials, XLB Materials.",
      low_means: "Giảm → sản xuất chậm → cyclicals chịu áp lực.",
      watch: "Core (ex-transport) ổn định hơn headline." },
    "DGORDER": { name: "Durable Goods Orders — Đơn hàng hàng bền", unit: "%MoM", freq: "Hàng tháng", source: "Census",
      what: "Đơn hàng mới hàng hóa bền (>3 năm: máy bay, xe, máy móc). Biến động mạnh do máy bay.",
      high_means: "Tăng → đầu tư/capex mạnh → XLI, XLK (thiết bị). Core capex orders quan trọng.",
      low_means: "Giảm → DN hoãn đầu tư → cyclicals yếu.",
      watch: "Core Capital Goods (ex-aircraft) = proxy capex thực." },
    "TTLCONS": { name: "Construction Spending — Chi tiêu xây dựng", unit: "%MoM", freq: "Hàng tháng", source: "Census",
      what: "Tổng chi xây dựng (nhà ở + phi nhà ở + công). Nhạy lãi suất.",
      high_means: "Tăng → xây dựng mạnh → tốt Materials, Industrials, Real Estate.",
      low_means: "Giảm → lãi suất cao đè xây dựng → xấu nhóm trên.",
      watch: "Tách residential vs nonresidential." },
    "PI": { name: "Personal Income — Thu nhập cá nhân", unit: "%MoM", freq: "Hàng tháng", source: "BEA",
      what: "Tổng thu nhập hộ gia đình (lương, đầu tư, chuyển nhượng).",
      high_means: "Tăng → sức mua mạnh → hỗ trợ chi tiêu, XLY Consumer Disc.",
      low_means: "Giảm → thu nhập yếu → tiêu dùng rủi ro.",
      watch: "Đi cùng Personal Spending + saving rate." },
    "PCE": { name: "Personal Spending (PCE) — Chi tiêu cá nhân", unit: "%MoM", freq: "Hàng tháng", source: "BEA",
      what: "Tổng chi tiêu tiêu dùng (~68% GDP). Động lực chính tăng trưởng.",
      high_means: "Tăng → tiêu dùng khỏe → XLY Consumer Disc, GDP.",
      low_means: "Giảm → tiêu dùng yếu → cảnh báo tăng trưởng.",
      watch: "Real (trừ lạm phát) quan trọng hơn nominal." },
    "TOTALSA": { name: "Total Vehicle Sales — Doanh số xe", unit: "Triệu xe (SAAR)", freq: "Hàng tháng", source: "BEA",
      what: "Doanh số xe mới. Hàng tiêu dùng lớn, nhạy lãi suất & niềm tin.",
      high_means: "Tăng → tiêu dùng mạnh, tín dụng tốt → XLY (auto), Financials (auto loans).",
      low_means: "Giảm → lãi suất/niềm tin đè → xấu auto, dealers.",
      watch: "16-17M = mạnh; <15M = yếu." },
    "WHLSLRIMSA": { name: "Wholesale Inventories — Tồn kho bán buôn", unit: "%MoM", freq: "Hàng tháng", source: "Census",
      what: "Hàng tồn khâu bán buôn. Tín hiệu chu kỳ tồn kho.",
      high_means: "Tồn kho tăng khi cầu yếu → có thể cắt sản xuất sau → bearish cyclicals (restocking chủ động thì bullish).",
      low_means: "Tồn kho thấp → cần restock → hỗ trợ sản xuất tương lai.",
      watch: "Đọc cùng inventory/sales ratio." },
    "RETAILIMSA": { name: "Retail Inventories — Tồn kho bán lẻ", unit: "%MoM", freq: "Hàng tháng", source: "Census",
      what: "Hàng tồn khâu bán lẻ. Tồn cao + bán chậm = áp lực giảm giá.",
      high_means: "Tồn vượt doanh số → nguy cơ giảm giá/cắt nhập → xấu retailer.",
      low_means: "Tồn thấp → cần nhập thêm → hỗ trợ đơn hàng.",
      watch: "Loại auto thường tách riêng." },
    "BOPGTB": { name: "Goods Trade Balance — Cán cân thương mại hàng hóa", unit: "Tỷ USD", freq: "Hàng tháng (advance)", source: "Census/BEA",
      what: "Xuất trừ nhập hàng hóa (bản advance ra sớm). Âm = thâm hụt.",
      high_means: "Thâm hụt thu hẹp → net exports đóng góp GDP dương.",
      low_means: "Thâm hụt nới rộng → kéo GDP; phản ánh cầu nội địa mạnh hoặc USD mạnh.",
      watch: "Advance Goods ra trước số đầy đủ ~1 tuần." },
    "PERMIT": { name: "Building Permits — Giấy phép xây dựng", unit: "Nghìn căn (SAAR)", freq: "Hàng tháng", source: "Census",
      what: "Giấy phép xây nhà — leading indicator của Housing Starts.",
      high_means: "Tăng → builders lạc quan → tốt Homebuilders, Materials, Real Estate.",
      low_means: "Giảm → cầu nhà yếu (lãi suất cao) → xấu nhóm nhà ở.",
      watch: "Đi trước Housing Starts; nhạy mortgage rate." },
    "HSN1F": { name: "New Home Sales — Doanh số nhà mới", unit: "Nghìn căn (SAAR)", freq: "Hàng tháng", source: "Census",
      what: "Số nhà MỚI xây bán được. Bổ sung Existing Home Sales (nhà cũ).",
      high_means: "Tăng → cầu nhà mạnh → tốt Homebuilders (DHI, LEN), Materials.",
      low_means: "Giảm → thị trường nhà nguội → xấu builders, mortgage.",
      watch: "Biến động mạnh, hay điều chỉnh; xem trend." },
    // ===== FED VÙNG — chỉ số/nhận định định lượng =====
    "CFNAI": { name: "CFNAI — Chỉ số Hoạt động Kinh tế Quốc gia (Chicago Fed)", unit: "Index chuẩn hoá (0 = trend)", freq: "Hàng tháng", source: "Federal Reserve Bank of Chicago",
      what: "Trung bình có trọng số của 85 chỉ báo kinh tế hàng tháng (sản xuất, lao động, tiêu dùng, nhà ở). Đo hoạt động kinh tế tổng thể so với xu hướng dài hạn.",
      high_means: "Trên 0 = tăng trưởng trên trend → kinh tế khỏe, hỗ trợ cyclicals (XLI, XLB, XLY). Trên +0.7 (theo MA3) = áp lực lạm phát từ tăng trưởng nóng.",
      low_means: "Dưới 0 = dưới trend. MA3 dưới −0.7 = tín hiệu suy thoái đã bắt đầu (lịch sử rất tin cậy) → defensive (XLP, XLU, XLV).",
      why: "Một trong những thước đo 'nhịp' kinh tế tổng hợp tốt nhất; Fed dùng để đọc đà tăng trưởng + áp lực lạm phát. Xem CFNAI-MA3 (đường trung bình 3 tháng) để bỏ nhiễu.",
      watch: "Ngưỡng then chốt: MA3 = −0.7 (suy thoái) và +0.7 (lạm phát). Bản thân số tháng đơn rất nhiễu." },
    "NFCI": { name: "NFCI — Điều kiện Tài chính Quốc gia (Chicago Fed)", unit: "Index chuẩn hoá (0 = TB lịch sử)", freq: "Hàng tuần (thứ Tư)", source: "Federal Reserve Bank of Chicago",
      what: "Tổng hợp 105 chỉ báo về thị trường tiền tệ, trái phiếu, cổ phiếu, ngân hàng (truyền thống + shadow). Đo độ chặt/lỏng của điều kiện tài chính.",
      high_means: "Trên 0 = điều kiện tài chính THẮT CHẶT hơn trung bình (spreads rộng, đòn bẩy giảm, biến động cao) → rủi ro risk-off, áp lực lên equities & credit.",
      low_means: "Dưới 0 = NỚI LỎNG hơn trung bình (thanh khoản dồi dào, spreads hẹp) → môi trường risk-on, hỗ trợ tài sản rủi ro.",
      why: "Leading cho tăng trưởng & tín dụng; Fed theo dõi để đánh giá truyền dẫn chính sách. Thắt chặt nhanh = cảnh báo stress (vd ngân hàng 3/2023).",
      watch: "Xem hướng & tốc độ thay đổi quan trọng hơn mức. So với ANFCI để tách phần độc lập với chu kỳ kinh tế." },
    "ANFCI": { name: "ANFCI — Điều kiện Tài chính ĐÃ điều chỉnh (Chicago Fed)", unit: "Index chuẩn hoá", freq: "Hàng tuần (thứ Tư)", source: "Federal Reserve Bank of Chicago",
      what: "NFCI sau khi loại bỏ phần biến động giải thích được bởi chu kỳ kinh tế & lạm phát. Cho biết điều kiện tài chính LỎNG/CHẶT hơn mức 'đáng lẽ' so với trạng thái kinh tế.",
      high_means: "Trên 0 = tài chính chặt hơn mức kinh tế biện minh → có thể là stress thực sự, đáng lo hơn NFCI thuần.",
      low_means: "Dưới 0 = lỏng hơn mức đáng lẽ → điều kiện tài chính đang hỗ trợ vượt mức (có thể nuôi bong bóng/rủi ro).",
      why: "Tách 'tài chính dẫn dắt' khỏi 'kinh tế dẫn dắt' — hữu ích để biết Fed có đang mất kiểm soát truyền dẫn không.",
      watch: "Phân kỳ ANFCI vs NFCI = tín hiệu đáng chú ý." },
    "WEI": { name: "WEI — Chỉ số Kinh tế Hàng tuần (New York Fed)", unit: "% (≈ GDP YoY)", freq: "Hàng tuần", source: "Federal Reserve Bank of New York (Lewis-Mertens-Stock)",
      what: "Nowcast tần suất tuần từ 10 chuỗi (claims, bán lẻ, sản xuất điện, thép, niềm tin…), scale về đơn vị tăng trưởng GDP YoY. Đọc 'nhịp' kinh tế thời gian thực.",
      high_means: "WEI cao (vd >2-3%) = tăng trưởng thực mạnh → risk-on, cyclicals hưởng lợi.",
      low_means: "WEI giảm nhanh/âm = hoạt động co lại theo thời gian thực → cảnh báo sớm suy yếu trước số tháng/quý chính thức.",
      why: "Cập nhật tuần → bắt bước ngoặt sớm hơn nhiều dữ liệu official có độ trễ. Hữu ích quanh cú sốc (COVID, ngân hàng).",
      watch: "Xem xu hướng 4-13 tuần, không phải tuần đơn; so với GDPNow (Atlanta) để đối chiếu nowcast." },
    // ===== FED VÙNG — DỰ BÁO & KỲ VỌNG (tải Excel từ Philly/NY Fed) =====
    "SPF_GDP": { name: "SPF — Dự báo tăng trưởng GDP (4 quý tới)", unit: "% annualized", freq: "Hàng quý", source: "Philadelphia Fed — Survey of Professional Forecasters",
      what: "Trung bình median của giới dự báo chuyên nghiệp về tốc độ tăng GDP thực 4 quý tới. Đại diện kỳ vọng đồng thuận thị trường.",
      high_means: "Dự báo tăng trưởng cao → kỳ vọng kinh tế khỏe → hỗ trợ cyclicals (XLI, XLY, XLB), risk-on.",
      low_means: "Dự báo hạ → giới chuyên gia lo tăng trưởng chậm → phòng thủ (XLP, XLU, XLV), rủi ro suy thoái.",
      why: "SPF là khảo sát dự báo lâu đời & uy tín nhất (từ 1968). Khi SPF hạ dự báo nhiều quý liên tiếp = tín hiệu chu kỳ chậm lại đáng tin.",
      watch: "Quan trọng là HƯỚNG điều chỉnh qua các quý, không phải mức tuyệt đối. So với GDPNow (nowcast) và WEI." },
    "SPF_CPI": { name: "SPF — Dự báo lạm phát CPI (năm tới)", unit: "% YoY", freq: "Hàng quý", source: "Philadelphia Fed — SPF",
      what: "Dự báo median lạm phát CPI trung bình năm tới của giới dự báo chuyên nghiệp.",
      high_means: "Dự báo lạm phát >2.5% kéo dài → kỳ vọng Fed hawkish lâu hơn → áp lực lên bonds, growth stocks.",
      low_means: "Về gần 2% → kỳ vọng disinflation → Fed dễ dovish → tốt cho equities, đặc biệt tech/REITs.",
      why: "Kỳ vọng lạm phát của chuyên gia ảnh hưởng định giá trái phiếu & dự báo Fed path. Neo trên 2% lâu = Fed lo de-anchor.",
      watch: "So với mục tiêu Fed 2% (đường tham chiếu) và SCE (kỳ vọng hộ gia đình)." },
    "NYFED_RSTAR": { name: "r* — Lãi suất tự nhiên (NY Fed, HLW · US)", unit: "%", freq: "Hàng quý", source: "New York Fed — Holston-Laubach-Williams",
      what: "Ước lượng lãi suất thực trung tính (neutral real rate) — mức r mà nền kinh tế cân bằng (không kích thích/thắt chặt) trong dài hạn.",
      high_means: "r* tăng → Fed có thể giữ lãi suất cao hơn mà vẫn 'trung tính' → trần định giá thấp hơn cho tài sản dài hạn (growth, bonds).",
      low_means: "r* thấp → môi trường lãi suất thấp cấu trúc → hỗ trợ định giá cao, duration-sensitive (tech, REITs).",
      why: "r* là 'mỏ neo' cho terminal rate của Fed. Tranh luận r* tăng hậu-COVID là chủ đề vĩ mô lớn — quyết định mức 'higher for longer'.",
      watch: "Ước lượng có sai số lớn & điều chỉnh; xem xu hướng nhiều quý. So với Fed Funds thực (DFF − lạm phát)." },
    "SCE_INFL_1Y": { name: "SCE — Kỳ vọng lạm phát 1 năm (NY Fed)", unit: "% (median hộ gia đình)", freq: "Hàng tháng", source: "New York Fed — Survey of Consumer Expectations",
      what: "Median kỳ vọng lạm phát 1 năm tới của hộ gia đình Mỹ (khảo sát ~1,300 hộ/tháng).",
      high_means: "Kỳ vọng tăng → nguy cơ lạm phát tự thành hiện thực (wage-price) → Fed buộc hawkish. Xấu cho bonds, growth.",
      low_means: "Kỳ vọng hạ về 2-3% → lạm phát kỳ vọng được neo → Fed yên tâm dovish hơn.",
      why: "Fed coi kỳ vọng lạm phát là then chốt: nếu de-anchor thì rất khó kéo lại. SCE bổ sung góc nhìn hộ gia đình bên cạnh Michigan.",
      watch: "So với Michigan 1Y inflation expectation và breakeven 10Y (T10YIE). 3Y SCE quan trọng cho neo dài hạn." },
    // ===== TỒN KHO DẦU KHÍ (EIA) — không có trên FRED, lấy từ EIA API =====
    "EIA_CRUDE": {
      name: "Crude Oil Stocks — Tồn kho dầu thô (ex-SPR)",
      unit: "Nghìn thùng (level)",
      freq: "Hàng tuần (EIA, thứ Tư)",
      source: "EIA (Cơ quan Thông tin Năng lượng Mỹ)",
      what: "Tổng tồn kho dầu thô thương mại Mỹ (không tính Kho Dự trữ Chiến lược SPR).",
      high_means: "Tồn kho tăng → cung dư/cầu yếu → áp lực GIẢM giá dầu. Xấu cho XLE (Energy), tốt cho nhóm nhạy chi phí năng lượng (vận tải, hàng không, hóa chất).",
      low_means: "Tồn kho giảm mạnh (draw) → cầu mạnh/cung thắt → áp lực TĂNG giá dầu → hỗ trợ XLE, áp lực lạm phát năng lượng.",
      why: "Số tuần EIA là một trong những catalyst giao dịch dầu lớn nhất; so với forecast & mức theo mùa quan trọng hơn level tuyệt đối.",
      watch: "Đối chiếu với draw/build theo mùa và Cushing (điểm giao COMEX). Build bất thường mùa hè = bearish dầu.",
    },
    "EIA_GASOLINE": {
      name: "Gasoline Stocks — Tồn kho xăng",
      unit: "Nghìn thùng (level)",
      freq: "Hàng tuần (EIA)",
      source: "EIA",
      what: "Tổng tồn kho xăng thành phẩm Mỹ.",
      high_means: "Tồn kho xăng cao → biên lọc dầu (crack spread) hẹp, giá bơm có thể giảm. Tốt cho tiêu dùng, xấu cho refiner.",
      low_means: "Tồn kho xăng thấp (đặc biệt mùa lái xe hè) → giá bơm tăng → áp lực CPI năng lượng + sức mua tiêu dùng.",
      why: "Xăng là cầu nối giá dầu → túi tiền người tiêu dùng; mùa hè (driving season) là cao điểm.",
      watch: "Theo dõi cùng crude + crack spread; draw mạnh trước hè = bullish refiner.",
    },
    "EIA_DISTILLATE": {
      name: "Distillate Stocks — Tồn kho dầu chưng cất (diesel/heating)",
      unit: "Nghìn thùng (level)",
      freq: "Hàng tuần (EIA)",
      source: "EIA",
      what: "Tồn kho dầu chưng cất (diesel + dầu sưởi) — gắn với vận tải hàng hóa & công nghiệp.",
      high_means: "Tồn kho cao → cầu công nghiệp/vận tải yếu → tín hiệu tăng trưởng chậm; giá diesel hạ.",
      low_means: "Tồn kho thấp → cầu vận tải/công nghiệp mạnh hoặc cung thắt → giá diesel tăng (chi phí logistics).",
      why: "Distillate phản ánh sức khỏe vận tải & sản xuất — proxy hữu ích cho hoạt động kinh tế thực.",
      watch: "Đặc biệt quan trọng mùa đông (heating oil); mức thấp + lạnh = spike giá.",
    },
    // ===== ISM PMI (không có trên FRED — paywall; dựng từ scrape, dày dần mỗi tháng) =====
    "ISM_MFG": {
      name: "ISM Manufacturing PMI — Chỉ số sản xuất ISM",
      unit: "Index, 50 = không đổi",
      freq: "Hàng tháng (ngày làm việc đầu tiên)",
      source: "Institute for Supply Management",
      what: "Khảo sát purchasing managers ngành sản xuất về New Orders, Production, Employment, Supplier Deliveries, Inventories. Trên 50 = mở rộng, dưới 50 = thu hẹp.",
      high_means: "Trên 50 (đặc biệt > 53) = sản xuất mở rộng → tốt cho XLI Industrials, XLB Materials, XLE Energy; copper & WTI thường tăng theo.",
      low_means: "Dưới 50 = thu hẹp; dưới 45 = vùng suy thoái → cyclicals chịu áp lực, dòng tiền về defensive (XLV, XLP, XLU).",
      why: "Một trong những leading indicator được trade nhiều nhất. Component 'New Orders' (cầu sắp tới) và 'Prices Paid' (áp lực lạm phát) đặc biệt quan trọng.",
      watch: "Trend 3 tháng quan trọng hơn 1 con số. Mốc 50 là ranh giới expansion/contraction; 42.5 ~ ranh giới suy thoái toàn nền kinh tế.",
    },
    "ISM_SVC": {
      name: "ISM Services PMI — Chỉ số dịch vụ ISM (Non-Manufacturing)",
      unit: "Index, 50 = không đổi",
      freq: "Hàng tháng (ngày làm việc thứ 3)",
      source: "Institute for Supply Management",
      what: "Khảo sát purchasing managers ngành dịch vụ (~70% GDP Mỹ) về Business Activity, New Orders, Employment, Prices. Trên 50 = mở rộng.",
      high_means: "Trên 50 = dịch vụ mở rộng → nền kinh tế khỏe; tốt cho tiêu dùng, tài chính. Nhưng quá nóng + Prices cao = lạm phát dịch vụ dai dẳng → hawkish.",
      low_means: "Dưới 50 (hiếm) = báo động suy thoái thực sự vì dịch vụ rất resilient → bán tháo rủi ro, defensive bid.",
      why: "Quan trọng hơn Mfg PMI về vĩ mô vì dịch vụ chiếm tỷ trọng lớn nhất GDP. Component 'Prices Paid' là tín hiệu lạm phát dịch vụ Fed theo dõi sát.",
      watch: "Mốc 50; Prices Paid > 60 = áp lực lạm phát dịch vụ. So với ISM Mfg để đọc bức tranh cả 2 khu vực.",
    },
    // ===== NHÀ Ở =====
    "PENDINGHOMES": {
      name: "Pending Home Sales Index — Chỉ số doanh số nhà chờ bán (NAR)",
      unit: "Index 2001=100",
      freq: "Hàng tháng (NAR)",
      source: "National Association of Realtors",
      what: "Số hợp đồng mua nhà cũ ĐÃ KÝ nhưng chưa hoàn tất (pending). Leading indicator cho Existing Home Sales 1-2 tháng sau.",
      high_means: "Hợp đồng tăng → thị trường nhà ấm lên → tốt cho Real Estate, Financials (mortgage), Home improvement, Materials.",
      low_means: "Hợp đồng giảm → cầu nhà nguội (thường do lãi suất cao) → xấu cho REITs, homebuilders, mortgage lenders.",
      why: "Đi TRƯỚC doanh số nhà hoàn tất → tín hiệu sớm về sức khỏe thị trường nhà, vốn siêu nhạy lãi suất. (Không có trên FRED — dựng từ scrape, dày dần mỗi tháng.)",
      watch: "Nhạy với mortgage 30Y; bật mạnh khi lãi suất hạ. So với forecast quan trọng hơn level.",
    },
    "HOUST": {
      name: "Housing Starts — Số nhà mới khởi công",
      unit: "Nghìn căn (annualized)",
      freq: "Hàng tháng",
      source: "Census Bureau",
      what: "Số căn nhà ở mà builders bắt đầu xây trong tháng (single + multi-family).",
      high_means: "Builders lạc quan → cầu nhà ở mạnh. Tốt cho Homebuilders (DR Horton, Lennar), vật liệu (Materials), REITs.",
      low_means: "Cầu nhà ở yếu (thường do lãi suất cao). Xấu cho Real Estate, Materials, Financials (mortgage).",
      why: "Housing siêu nhạy với lãi suất. Là leading indicator của economic cycle — nhà ở thường downturn TRƯỚC khi recession.",
      watch: "Mortgage rate 30Y > 7% thường kéo housing starts xuống. Theo dõi cùng Building Permits (forward indicator).",
    },
    "EXHOSLUSM495S": {
      name: "Existing Home Sales — Doanh số nhà cũ đã bán",
      unit: "Triệu căn (annualized)",
      freq: "Hàng tháng",
      source: "National Association of Realtors",
      what: "Số căn nhà cũ (đã từng được sở hữu) được giao dịch.",
      high_means: "Thị trường nhà ở thanh khoản, sôi động → tốt cho Real Estate, Financials (mortgage), Home improvement (Home Depot).",
      low_means: "Thị trường nhà ở đóng băng → 'lock-in effect' do lãi suất cao → xấu cho realtors, mortgage lenders.",
      why: "Existing home sales chiếm ~90% giao dịch nhà ở. Phản ánh hành vi của chủ nhà hiện tại — họ có sẵn sàng bán không?",
      watch: "Khi mortgage rate cao, nhiều chủ nhà 'mắc kẹt' với mortgage 3% cũ, không muốn bán → inventory thấp → giá vẫn đỡ.",
    },
    "CSUSHPINSA": {
      name: "Case-Shiller Home Price Index — Chỉ số giá nhà",
      unit: "Index Jan 2000=100",
      freq: "Hàng tháng (có lag 2 tháng)",
      source: "S&P / CoreLogic",
      what: "Theo dõi giá bán nhà ở repeat-sale (cùng 1 căn bán nhiều lần). Loại trừ hiệu ứng mix (chất lượng nhà khác nhau).",
      high_means: "Giá nhà tăng → wealth effect → tốt cho Discretionary spending, nhưng cũng làm housing kém affordable.",
      low_means: "Giá nhà giảm → wealth effect âm → xấu cho consumer.",
      why: "Là benchmark chuẩn cho giá nhà Mỹ. Sub-component của CPI 'Shelter' dùng phương pháp khác (Owners' Equivalent Rent) nhưng có liên hệ.",
      watch: "YoY decline 2 quý liên tiếp = housing bust signal (đã xảy ra 2006-2009, 2022 mini-bust).",
    },

    // ===== LÃI SUẤT =====
    "DFF": {
      name: "Fed Funds Rate — Lãi suất Fed Funds (effective)",
      unit: "% năm",
      freq: "Hàng ngày",
      source: "Federal Reserve",
      what: "Lãi suất qua đêm mà các ngân hàng cho nhau vay từ dự trữ tại Fed. Fed thiết lập target range; effective rate dao động trong range đó.",
      high_means: "Monetary policy thắt chặt → equities chịu áp lực (đặc biệt growth/tech). USD↑, yields↑. Tốt cho Financials (NIM↑), xấu cho REITs/Utilities.",
      low_means: "Monetary policy lỏng → equities thường rally, growth/tech hưởng lợi. Xấu cho Financials (NIM↓).",
      why: "Là **lãi suất chính sách** quan trọng nhất. Mọi lãi suất khác đều tham chiếu nó. Fed họp 8 lần/năm (FOMC) để quyết định.",
      watch: "Mức 'neutral' ước tính 2.5-3%. Trên đó = restrictive; dưới = accommodative. Theo dõi 'dot plot' để hiểu kỳ vọng Fed.",
    },
    "DGS10": {
      name: "10Y Treasury Yield — Lợi suất trái phiếu chính phủ 10 năm",
      unit: "% năm",
      freq: "Hàng ngày",
      source: "U.S. Treasury",
      what: "Lợi suất nhà đầu tư yêu cầu để giữ trái phiếu chính phủ Mỹ 10 năm.",
      high_means: "Yield cao → discount rate cho stock valuation cao → P/E ratios chịu áp lực (đặc biệt growth/tech). Mortgage rate↑ → housing xấu. USD↑.",
      low_means: "Yield thấp → tốt cho equities, REITs, Utilities. Có thể signal recession risk (flight to safety).",
      why: "Là **benchmark global** cho borrowing cost. Mortgage rate Mỹ track theo 10Y yield. Mọi DCF model đều dùng nó.",
      watch: "Trên 4.5% thường gây stress cho equities. Spike nhanh (>50bps/tuần) = market disruption.",
    },
    "DGS2": {
      name: "2Y Treasury Yield — Lợi suất 2 năm",
      unit: "% năm",
      freq: "Hàng ngày",
      source: "U.S. Treasury",
      what: "Lợi suất trái phiếu 2 năm. Nhạy với kỳ vọng Fed Funds trong 2 năm tới.",
      high_means: "Thị trường kỳ vọng Fed sẽ giữ/tăng lãi suất. Hawkish narrative.",
      low_means: "Thị trường kỳ vọng Fed sẽ cắt lãi suất. Dovish.",
      why: "2Y phản ánh trực tiếp Fed expectations. Khi 2Y giảm mạnh trong vài tuần = market đang price-in rate cuts.",
      watch: "So sánh với Fed Funds Rate: 2Y < Fed Funds = market expects cuts; 2Y > Fed Funds = market expects more hikes.",
    },
    "DGS3MO": {
      name: "3M Treasury Yield — Lợi suất 3 tháng (T-bill)",
      unit: "% năm",
      freq: "Hàng ngày",
      source: "U.S. Treasury",
      what: "Lãi suất ngắn hạn, sát với Fed Funds Rate.",
      high_means: "Lãi suất ngắn hạn cao → money market funds hấp dẫn → có thể rút tiền khỏi equities.",
      low_means: "Lãi suất ngắn hạn thấp → tiền tìm yield cao hơn → flow vào equities/credit.",
      why: "3M T-bill là cash equivalent thực sự. Dùng để tính 10Y-3M spread (một trong những recession predictor chính xác nhất theo NY Fed).",
      watch: "Khi 10Y < 3M (đảo ngược) → recession trong 6-18 tháng (theo lịch sử).",
    },
    "T10Y2Y": {
      name: "10Y-2Y Spread — Chênh lệch yield 10 năm vs 2 năm",
      unit: "% (điểm phần trăm)",
      freq: "Hàng ngày",
      source: "FRED tính",
      what: "Khoảng cách giữa lợi suất 10Y và 2Y. Đo độ dốc của yield curve.",
      high_means: "Curve steep → kỳ vọng tăng trưởng/lạm phát tương lai. Tốt cho Financials (NIM↑). Risk-on.",
      low_means: "Curve flat hoặc inverted (âm) → kỳ vọng suy thoái. **Inversion là recession predictor**. Xấu cho Financials.",
      why: "Là **chỉ số dự báo recession đáng tin cậy nhất trong lịch sử Mỹ**. Mọi recession từ 1970 đều có inversion trước đó 6-24 tháng.",
      watch: "Inversion (< 0) duy trì > 6 tháng = warning đỏ. Khi inversion 'un-invert' (về dương) thường là lúc recession bắt đầu — counter-intuitive.",
    },

    // ===== CROSS-ASSET =====
    "DTWEXBGS": {
      name: "DXY — Chỉ số USD (Trade-Weighted Broad)",
      unit: "Index, Jan 2006=100",
      freq: "Hàng ngày",
      source: "Federal Reserve",
      what: "Đo sức mạnh USD so với rổ tiền tệ của các đối tác thương mại chính (EUR, CNY, JPY, GBP, CAD…). Trade-weighted để phản ánh tầm quan trọng kinh tế.",
      high_means: "USD mạnh → **xấu cho multinationals** (Tech, Materials, Energy do FX drag khi đổi doanh thu nước ngoài về USD). Xấu cho commodities (denominated in USD). Xấu cho EM equities. Tốt cho importers, US domestic small-caps.",
      low_means: "USD yếu → tốt cho multinationals (FX tailwind), tốt cho commodities (oil, copper, gold thường ngược chiều USD), tốt cho EM.",
      why: "**USD là biến số macro quan trọng thứ 2 sau Fed Funds**. ~40% doanh thu S&P 500 từ ngoài Mỹ — DXY tăng 5% = ~2% EPS headwind cho S&P. Là tín hiệu risk-on/off cross-asset.",
      watch: "DXY > 105 = USD mạnh, headwind cho cyclicals. > 110 = stress global. Thường ngược chiều với gold, copper, EM equities. Khi Fed dovish + global growth ổn → DXY giảm.",
    },
    "VIXCLS": {
      name: "VIX — Chỉ số biến động (Fear Gauge)",
      unit: "Index, % annualized",
      freq: "Hàng ngày",
      source: "CBOE",
      what: "Đo expected volatility 30 ngày của S&P 500, tính từ option prices. 'Chỉ số sợ hãi' của Wall Street.",
      high_means: "Vol cao → market đang stress, risk-off. Equities thường đã giảm hoặc đang giảm. Tốt cho cash/Treasuries, xấu cho cyclicals/Tech.",
      low_means: "Vol thấp → complacency. Equities thường rally hoặc đứng yên. NHƯNG VIX rất thấp (<12) + rally kéo dài = warning, market có thể overconfident.",
      why: "Là **risk appetite indicator** chính. VIX spike > 30 hiếm khi xảy ra → khi xảy ra thường là buying opportunity (lịch sử). VIX > 40 = panic.",
      watch: "VIX < 15: risk-on phase. 15-20: neutral. 20-30: cautious. >30: stress. Theo dõi 'VIX term structure' (contango vs backwardation) — backwardation (front > back) = panic ngắn hạn.",
    },
    "DCOILWTICO": {
      name: "WTI Crude Oil — Giá dầu thô Mỹ",
      unit: "USD/thùng",
      freq: "Hàng ngày",
      source: "EIA / Cushing OK spot",
      what: "Giá dầu thô West Texas Intermediate — benchmark giá dầu Mỹ. Brent là benchmark global.",
      high_means: "Dầu tăng → tốt cho XLE Energy. Xấu cho Discretionary, Industrials (transport cost), Airlines. Có thể đẩy CPI Energy → Fed hawkish hơn.",
      low_means: "Dầu giảm → tốt cho consumer (savings), tốt cho Airlines, Transport. Xấu cho XLE Energy. Có thể signal demand destruction (recession risk) hoặc OPEC tăng supply.",
      why: "Dầu là input cost của toàn nền kinh tế. WTI giảm 20% trong 3 tháng thường = recession warning (demand destruction). WTI tăng 30% = stagflation risk.",
      watch: "WTI > $90 = áp lực CPI. < $60 = demand weakness signal. OPEC+ meetings, US rig count (Baker Hughes thứ Sáu), inventory data (EIA thứ Tư) là catalysts chính.",
    },
    "BAMLH0A0HYM2": {
      name: "HY OAS — Chênh lệch trái phiếu rác (High-Yield spread)",
      unit: "% (điểm phần trăm)",
      freq: "Hàng ngày",
      source: "ICE BofA",
      what: "Spread giữa yield của trái phiếu junk (BB và thấp hơn) so với Treasury cùng kỳ hạn. Đo 'risk premium' nhà đầu tư đòi để giữ junk bonds.",
      high_means: "Spread rộng = nhà đầu tư đòi premium cao = lo lắng default. **Mạnh tín hiệu risk-off**. Xấu cho equities (đặc biệt cyclicals, Financials), tốt cho Treasuries.",
      low_means: "Spread hẹp = thị trường tin tưởng credit, risk-on. Tốt cho equities và high-yield bonds. Nhưng quá hẹp (<3%) = complacency, warning.",
      why: "**HY spread là leading indicator tốt hơn equity** cho recession. Mỗi recession có HY spread blow out trước/cùng lúc với equity crash. Theo dõi widen rate hơn level.",
      watch: "< 3% = euphoria. 3-5% = neutral. 5-7% = caution. > 7% = stress. > 10% = panic/recession. Widen 100bps trong 1 tuần = red flag.",
    },
    "BAMLC0A0CM": {
      name: "IG OAS — Chênh lệch trái phiếu investment-grade",
      unit: "% (điểm phần trăm)",
      freq: "Hàng ngày",
      source: "ICE BofA",
      what: "Spread giữa yield của trái phiếu doanh nghiệp IG (BBB và cao hơn) so với Treasury.",
      high_means: "IG spread widen → credit stress lan ra cả investment-grade → suy thoái thực sự. Worse than HY widening (vì IG là 'high quality').",
      low_means: "IG spread tight → credit khoẻ, tốt cho Financials và cyclicals.",
      why: "IG spread ổn định hơn HY. Khi IG widen mạnh = stress thực sự, không phải mood swing. So sánh IG vs HY: HY widen nhưng IG ổn = phân hoá; cả 2 widen = systemic risk.",
      watch: "< 1% = risk-on. 1-1.5% = neutral. > 1.5% = caution. > 2% = stress.",
    },
    "T10YIE": {
      name: "10Y Inflation Breakeven — Kỳ vọng lạm phát 10 năm",
      unit: "% năm",
      freq: "Hàng ngày",
      source: "FRED tính (10Y nominal − 10Y TIPS)",
      what: "Khác biệt giữa yield của Treasury danh nghĩa 10 năm và TIPS 10 năm = lạm phát kỳ vọng trung bình trong 10 năm tới do thị trường tin.",
      high_means: "Breakeven cao = thị trường tin lạm phát sẽ cao kéo dài → Fed hawkish hơn. Xấu cho long-duration bonds, Tech, REITs.",
      low_means: "Breakeven thấp = thị trường tin lạm phát quay về 2% → Fed dovish. Tốt cho bonds, Tech, REITs.",
      why: "Là **chỉ số kỳ vọng lạm phát thị trường-based** (vs survey-based như Michigan). Fed theo dõi để xem kỳ vọng có 'anchored' không. Nếu breakeven spike > 3% và stay → Fed buộc phải hành động.",
      watch: "2-2.5% = anchored ở target. > 2.5% = drift up, Fed lo. < 2% = disinflation, có thể deflation risk. So với CPI YoY thực: nếu breakeven thấp nhưng CPI cao → thị trường tin lạm phát sẽ giảm.",
    },
  },

  // Cross-asset từ yfinance (không có FRED ID)
  byCrossAssetTicker: {
    "GC=F": {
      name: "Gold Futures — Vàng",
      ticker: "GC=F",
      unit: "USD/oz",
      what: "Hợp đồng tương lai vàng. Vàng là safe-haven asset, store of value.",
      drivers: "Inverse với USD và real yields (10Y nominal - inflation expectations). Khi real yields giảm → cost of holding gold giảm → gold tăng. Risk-off đẩy vàng tăng. Geopolitics (chiến tranh, sanctions) tăng vàng. Central bank buying (China, Russia, India) là buoy quan trọng.",
      thrives_when: "Real yields giảm, USD yếu, geopolitical tension, recession fear, central bank tích trữ.",
      struggles_when: "Real yields tăng (Fed hawkish), USD mạnh, risk-on extreme, market complacency.",
      sector_signal: "Vàng tăng mạnh + USD yếu = Materials (mining stocks) hưởng lợi (NEM, GOLD). Vàng tăng + equity giảm = defensive positioning advised.",
    },
    "HG=F": {
      name: "Copper Futures — Đồng (Dr. Copper)",
      ticker: "HG=F",
      unit: "USD/lb",
      what: "Đồng được gọi là 'Dr. Copper' vì khả năng dự báo kinh tế — đồng được dùng trong xây dựng, sản xuất, EV, hạ tầng điện.",
      drivers: "China demand (50%+ tiêu thụ global), USD (inverse), supply disruptions (Chile, Peru mines), EV/renewable buildout (long-term demand).",
      thrives_when: "China stimulus, global growth strong, infrastructure spending, EV adoption tăng tốc, USD yếu.",
      struggles_when: "China slowdown, recession, USD mạnh, supply increase.",
      sector_signal: "**Copper là leading indicator cho global growth**. Copper rally → bullish cyclicals (XLI Industrials, XLB Materials). Copper crash → recession signal, defensive positioning.",
    },
    "BTC-USD": {
      name: "Bitcoin",
      ticker: "BTC-USD",
      unit: "USD",
      what: "Tiền điện tử lớn nhất. Trade như risk asset extreme, không phải digital gold (mặc dù market narrative đôi khi vậy).",
      drivers: "Risk appetite (correlated với QQQ trong vài năm gần đây), liquidity (Fed dovish + USD yếu = BTC tăng), regulatory news (ETF approvals, SEC actions), halving cycle (mỗi 4 năm), institutional adoption.",
      thrives_when: "Fed dovish, USD yếu, risk-on extreme, ETF flows positive, halving year.",
      struggles_when: "Fed hawkish, USD mạnh, equity vol spike, regulatory crackdown, exchange failures.",
      sector_signal: "BTC trade như leveraged QQQ → BTC rally mạnh thường confirms tech/crypto-adjacent stocks rally (MSTR, COIN, miners). BTC crash → risk-off signal across all crypto-exposed names.",
    },
  },

  // ===== 11 GICS SECTORS (SPDR Select Sector ETFs) =====
  bySectorTicker: {
    "XLK": {
      name: "Technology — Công nghệ",
      etf: "XLK",
      weight_sp500: "~30%",
      top_holdings: "Apple, Microsoft, Nvidia, Broadcom, Adobe",
      what: "Phần mềm, bán dẫn, dịch vụ IT, phần cứng. Sector lớn nhất S&P 500.",
      macro_drivers: "Rất nhạy với lãi suất (DCF discount): yields ↓ = tech ↑. Khi 10Y yield giảm 50bps, XLK thường outperform SPY 3-5%. Cũng nhạy với AI capex (hyperscaler guidance Microsoft, Google, Amazon, Meta), bán dẫn cycle.",
      thrives_when: "Dovish Fed, yields giảm, growth phase, AI cycle tăng tốc.",
      struggles_when: "Hawkish Fed (yields tăng mạnh), valuation stretched, AI bubble fears, China tariffs/export controls trên bán dẫn.",
      key_signals: "10Y Treasury Yield, FOMC dot plot, NVDA/MSFT earnings guidance, ISM Services PMI (proxy cho enterprise software demand).",
    },
    "XLF": {
      name: "Financials — Tài chính",
      etf: "XLF",
      weight_sp500: "~13%",
      top_holdings: "Berkshire Hathaway, JPM, BAC, Wells Fargo, Goldman Sachs, BlackRock",
      what: "Ngân hàng lớn, broker-dealer, bảo hiểm, asset manager, fintech.",
      macro_drivers: "NIM (net interest margin) phụ thuộc yield curve: 10Y-2Y spread tăng = NIM mở rộng = banks ↑. Credit quality phụ thuộc unemployment/GDP. Brokers/asset managers phụ thuộc equity market activity.",
      thrives_when: "Yield curve steep (10Y-2Y > 1%), GDP growth mạnh, equity market rally, lãi suất ổn định ở mức cao.",
      struggles_when: "Yield curve inverted/flat, recession risk (NPL ↑), Fed cắt lãi nhanh (NIM compress), credit losses tăng.",
      key_signals: "T10Y2Y spread, Initial Jobless Claims (proxy credit risk), Fed Funds Rate, bank stress test results, KBW Bank Index.",
    },
    "XLE": {
      name: "Energy — Năng lượng",
      etf: "XLE",
      weight_sp500: "~4%",
      top_holdings: "Exxon Mobil, Chevron, ConocoPhillips, EOG Resources, Schlumberger",
      what: "Oil & gas E&P, refiners, oilfield services, pipelines. Không bao gồm renewables (đó là XLU/Utilities).",
      macro_drivers: "Giá dầu WTI/Brent — phụ thuộc OPEC+, US shale supply, China demand, geopolitics (Middle East, Russia). USD mạnh = oil yếu (inverse). Recession = demand destruction.",
      thrives_when: "Oil > $80, OPEC cut production, geopolitical tension, USD yếu, global growth strong.",
      struggles_when: "Oil < $60, OPEC tăng sản lượng, recession demand, USD mạnh, energy transition narrative.",
      key_signals: "WTI Crude price, OPEC+ meetings, US rig count (Baker Hughes), EIA inventories, China PMI.",
    },
    "XLV": {
      name: "Healthcare — Y tế",
      etf: "XLV",
      weight_sp500: "~12%",
      top_holdings: "UnitedHealth, Eli Lilly, J&J, AbbVie, Merck, Pfizer",
      what: "Dược phẩm (big pharma + biotech), thiết bị y tế, bảo hiểm sức khoẻ, dịch vụ y tế.",
      macro_drivers: "**Defensive** — ít nhạy với chu kỳ kinh tế (người ta luôn cần thuốc). Nhưng có risk chính sách: Medicare drug pricing (IRA), tariff trên thuốc nhập. Biotech nhạy với rates (DCF dài hạn).",
      thrives_when: "Slowdown/recession (defensive bid), drug pipeline breakthroughs (GLP-1, oncology), Republican admin (pro-pharma), low rates (biotech).",
      struggles_when: "Drug price reform threats (Medicare, IRA expansion), patent cliffs, FDA rejection, hawkish rates (biotech).",
      key_signals: "FDA approval calendar, GLP-1 sales data (LLY, NVO), CMS pricing rules, election cycles, M&A activity.",
    },
    "XLY": {
      name: "Consumer Discretionary — Tiêu dùng không thiết yếu",
      etf: "XLY",
      weight_sp500: "~10%",
      top_holdings: "Amazon, Tesla, Home Depot, McDonald's, Booking Holdings, Lowe's",
      what: "E-commerce, autos, luxury, restaurants, hotels, retail, homebuilders.",
      macro_drivers: "**Cyclical** — phụ thuộc trực tiếp vào consumer spending. Theo dõi: Retail Sales, Wage growth, Consumer Confidence, Unemployment. Big component Amazon thực tế là tech + retail. Tesla nhạy với rates.",
      thrives_when: "Consumer confidence high, wage growth > inflation, low unemployment, rate cuts, holiday season.",
      struggles_when: "Recession fears, gas prices spike (tiền dư ít hơn), consumer credit stress, wages chậm.",
      key_signals: "Retail Sales control group, Michigan Sentiment, Initial Jobless Claims, Home Depot/Lowe's earnings (housing proxy).",
    },
    "XLP": {
      name: "Consumer Staples — Tiêu dùng thiết yếu",
      etf: "XLP",
      weight_sp500: "~6%",
      top_holdings: "P&G, Costco, Walmart, Coca-Cola, PepsiCo, Philip Morris",
      what: "Thực phẩm, đồ uống, hàng gia dụng, thuốc lá, hypermarket.",
      macro_drivers: "**Defensive** — demand stable bất kể chu kỳ. Lo lắng chính: input cost (commodities), pricing power vs private label, FX (multinationals). Walmart/Costco trade more cyclical (consumer trade-down).",
      thrives_when: "Slowdown/recession (defensive bid), commodities giảm (margin tốt hơn), USD yếu (multinationals).",
      struggles_when: "Strong growth phase (under-perform), commodities spike, GLP-1 reducing snack consumption (KO, PEP, MDLZ headwind).",
      key_signals: "CPI Food/Beverages, USD index (DXY), commodity prices, GLP-1 user growth.",
    },
    "XLI": {
      name: "Industrials — Công nghiệp",
      etf: "XLI",
      weight_sp500: "~9%",
      top_holdings: "GE, Caterpillar, RTX, Honeywell, Lockheed, Union Pacific, Boeing",
      what: "Aerospace & defense, machinery, transportation (rail, air, trucking), construction, capital goods.",
      macro_drivers: "**Cyclical** — phụ thuộc capex doanh nghiệp, infrastructure spending, global trade. Defense subsector phụ thuộc geopolitics. Transports phụ thuộc economic activity.",
      thrives_when: "ISM Mfg PMI > 50, infrastructure spending (CHIPS, IRA capex), defense spending high, global growth.",
      struggles_when: "ISM Mfg < 45, recession, China slowdown (Caterpillar exposure), peace dividend (defense ↓).",
      key_signals: "ISM Manufacturing PMI, Durable Goods Orders ex-Aircraft, Dow Transports relative strength, Boeing 737 MAX deliveries.",
    },
    "XLB": {
      name: "Materials — Vật liệu",
      etf: "XLB",
      weight_sp500: "~2%",
      top_holdings: "Linde, Sherwin-Williams, Air Products, Freeport-McMoRan, Newmont",
      what: "Hoá chất, kim loại (đồng, nhôm, vàng), giấy/bao bì, vật liệu xây dựng.",
      macro_drivers: "Phụ thuộc commodity prices (copper, gold, lithium), global growth (đặc biệt China), USD strength (commodities denominated in USD).",
      thrives_when: "China stimulus, infrastructure build-out, USD yếu, EV/renewable demand cho copper/lithium.",
      struggles_when: "China slowdown, USD mạnh, commodity bear market, recession.",
      key_signals: "Copper price (Dr Copper — leading indicator global growth), China PMI, USD index, Baltic Dry Index.",
    },
    "XLU": {
      name: "Utilities — Tiện ích công cộng",
      etf: "XLU",
      weight_sp500: "~2.5%",
      top_holdings: "NextEra Energy, Southern, Duke Energy, Constellation Energy, Dominion",
      what: "Điện, gas, nước. Bao gồm regulated utilities và independent power producers (IPPs). Renewable energy đang chuyển sang đây.",
      macro_drivers: "**Bond proxy** — siêu nhạy với 10Y yield (inverse). Yields ↓ = XLU ↑. Gần đây có thêm narrative AI data center electricity demand → NextEra, Constellation tăng mạnh.",
      thrives_when: "Yields giảm, dovish Fed, recession (defensive), AI data center boom.",
      struggles_when: "Yields tăng mạnh, hawkish Fed, expansion phase (under-perform), regulated rate cases adverse.",
      key_signals: "10Y Treasury Yield, FOMC dot plot, electricity demand growth (EIA), AI capex announcements.",
    },
    "XLRE": {
      name: "Real Estate (REITs) — Bất động sản",
      etf: "XLRE",
      weight_sp500: "~2.5%",
      top_holdings: "Prologis, American Tower, Welltower, Equinix, Public Storage, Simon Property",
      what: "REITs (Real Estate Investment Trusts): industrial (Prologis), data centers (Equinix), cell towers (American Tower), residential, retail malls, healthcare facilities, storage.",
      macro_drivers: "**Bond proxy** — siêu nhạy với rates (inverse), thậm chí hơn XLU. Mortgage REITs (mREITs) cực nhạy. Data center REITs có narrative AI riêng.",
      thrives_when: "Yields giảm, Fed cut, recession (yields collapse), AI/cloud demand cho data centers.",
      struggles_when: "Yields tăng, hawkish Fed, office REIT secular decline (WFH), retail/mall REIT structural decline.",
      key_signals: "10Y Yield, 30Y mortgage rate, office occupancy rate, data center pricing power.",
    },
    "XLC": {
      name: "Communication Services — Truyền thông & Internet",
      etf: "XLC",
      weight_sp500: "~9%",
      top_holdings: "Meta (Facebook), Google (Alphabet A+C), Netflix, Disney, T-Mobile, Verizon",
      what: "Internet/social media (Meta, Alphabet, Netflix), media (Disney), telecom (Verizon, T-Mobile, AT&T), gaming (Take-Two, EA).",
      macro_drivers: "Hybrid: Meta + Google trade gần như tech (rate-sensitive, ad cycle). Telecom (T, VZ) defensive, yield-sensitive. Media disrupted bởi streaming.",
      thrives_when: "Ad spend recovery (digital ad → Meta, Google), AI infra (Google Cloud), low rates (telecom + tech parts).",
      struggles_when: "Ad recession (linked Retail Sales), antitrust action (Google search, Meta acquisitions), rate spike (yield-sensitive parts).",
      key_signals: "Digital ad spend (eMarketer), Meta/Google ad revenue guidance, antitrust rulings, streaming subscriber growth.",
    },
  },

  // Match release names from investing.com (or any generic name) to a category
  byNamePattern: [
    // Import/Export price indexes — map investing.com release names (gồm MoM/YoY) → FRED IR/IQ
    { match: /import price/i, useFredId: "IR" },
    { match: /export price/i, useFredId: "IQ" },
    // Fed vùng (nếu investing.com có liệt kê thì cũng chart được trong panel ngày)
    { match: /chicago fed national activity|cfnai/i, useFredId: "CFNAI" },
    { match: /national financial conditions|nfci/i, useFredId: "NFCI" },
    { match: /weekly economic index|\bwei\b/i, useFredId: "WEI" },
    // Non-FRED indicators (EIA petroleum stocks + NAR pending homes)
    { match: /pending home sales/i, useFredId: "PENDINGHOMES" },
    { match: /crude oil inventories/i, useFredId: "EIA_CRUDE" },
    { match: /gasoline inventories/i, useFredId: "EIA_GASOLINE" },
    { match: /distillate/i, useFredId: "EIA_DISTILLATE" },
    // ISM PMI — không có trên FRED (paywall); dùng pseudo-id dựng từ scrape (giá trị PMI thật)
    { match: /ism manufacturing pmi/i, useFredId: "ISM_MFG" },
    { match: /ism (non[- ]?manufacturing|services) pmi/i, useFredId: "ISM_SVC" },
    {
      match: /ism manufacturing prices/i,
      useFredId: "PPIFES",
      info_override: {
        name: "ISM Mfg Prices Paid",
        unit: "Index, 50 = không đổi",
        freq: "Hàng tháng",
        source: "ISM",
        what: "Sub-component 'Prices Paid' của ISM PMI — đo áp lực giá đầu vào của nhà sản xuất.",
        high_means: "Trên 70 = áp lực giá mạnh, inflation comeback risk; trên 80 = extreme. Xấu cho margin doanh nghiệp, có thể truyền dẫn vào CPI/PCE tháng sau.",
        low_means: "Dưới 50 = giá giảm, disinflation. Tốt cho margin, tốt cho XLK (lower input cost) và tổng thể equities.",
        why: "Là leading indicator cho PPI/CPI. Fed theo dõi sát.",
        watch: "Thay đổi MoM quan trọng. Drop >3 điểm trong 1 tháng = disinflation signal mạnh.",
      },
    },
    {
      match: /ism manufacturing (employment|new orders)/i,
      useFredId: "MANEMP",
    },
    { match: /core cpi/i, useFredId: "CPILFESL" },
    { match: /\bcpi\b/i, useFredId: "CPIAUCSL" },
    { match: /core pce/i, useFredId: "PCEPILFE" },
    { match: /\bpce\b/i, useFredId: "PCEPI" },
    { match: /core ppi|ppi.*(ex|less).*(food|energy)/i, useFredId: "PPIFES" },
    { match: /\bppi\b/i, useFredId: "PPIFID" },
    { match: /nonfarm payroll|nfp/i, useFredId: "PAYEMS" },
    { match: /unemployment rate/i, useFredId: "UNRATE" },
    { match: /continuing.*claims|continued claims/i, useFredId: "CCSA" },
    { match: /(initial )?jobless claims|initial claims/i, useFredId: "ICSA" },
    { match: /average hourly earnings|avg hourly/i, useFredId: "CES0500000003" },
    { match: /jolts|job openings/i, useFredId: "JTSJOL" },
    { match: /\bgdp\b/i, useFredId: "A191RL1Q225SBEA" },
    { match: /retail sales/i, useFredId: "RSAFS" },
    { match: /industrial production/i, useFredId: "INDPRO" },
    { match: /housing starts/i, useFredId: "HOUST" },
    { match: /existing home sales/i, useFredId: "EXHOSLUSM495S" },
    { match: /case[- ]?shiller|home price/i, useFredId: "CSUSHPINSA" },
    { match: /michigan|consumer sentiment/i, useFredId: "UMCSENT" },
    { match: /consumer confidence/i, useFredId: "CSCICP03USM665S" },
    { match: /fed funds|federal funds|fomc/i, useFredId: "DFF" },
    { match: /10[- ]?year|10y/i, useFredId: "DGS10" },
    { match: /2[- ]?year|2y/i, useFredId: "DGS2" },
    { match: /3[- ]?month bill|3m bill/i, useFredId: "DGS3MO" },
    { match: /6[- ]?month bill|6m bill/i, useFredId: "DGS6MO" },
    { match: /construction spending/i, useFredId: "TTLCONS" },
    { match: /gdpnow|atlanta fed gdpnow/i, useFredId: "GDPNOW" },
    { match: /durable goods/i, useFredId: "DGORDER" },
    { match: /s&?p global manufacturing pmi|s&?p global mfg/i, useFredId: "MANEMP" },
    // Watchlist thêm (lao động / tăng trưởng / nhà ở)
    { match: /nonfarm productivity|labor productivity/i, useFredId: "OPHNFB" },
    { match: /unit labor cost/i, useFredId: "ULCNFB" },
    { match: /average weekly hours/i, useFredId: "AWHAETP" },
    { match: /factory orders/i, useFredId: "AMTMNO" },
    { match: /personal income/i, useFredId: "PI" },
    { match: /personal spending/i, useFredId: "PCE" },
    { match: /vehicle sales/i, useFredId: "TOTALSA" },
    { match: /wholesale inventories/i, useFredId: "WHLSLRIMSA" },
    { match: /retail inventories/i, useFredId: "RETAILIMSA" },
    { match: /goods trade balance/i, useFredId: "BOPGTB" },
    { match: /building permits/i, useFredId: "PERMIT" },
    { match: /new home sales/i, useFredId: "HSN1F" },
    // Fallback patterns for indicators not in our FRED list
    {
      match: /durable goods/i,
      info: {
        name: "Durable Goods Orders — Đơn hàng hàng bền",
        unit: "% MoM",
        freq: "Hàng tháng",
        source: "Census Bureau",
        what: "Đơn đặt hàng cho hàng hoá có tuổi thọ >3 năm (ô tô, máy bay, máy móc). Đo capex doanh nghiệp.",
        high_means: "Doanh nghiệp đầu tư mạnh → tốt cho Industrials, Materials.",
        low_means: "Doanh nghiệp thắt lưng buộc bụng → cyclicals chịu áp lực.",
        why: "Là leading indicator cho manufacturing và GDP. Sub-component 'Core capex' (ex-defense, ex-aircraft) ít nhiễu hơn.",
        watch: "Volatile vì các đơn hàng máy bay lớn. Theo dõi MA 3 tháng.",
      },
    },
    {
      match: /ism manufacturing|manufacturing pmi/i,
      info: {
        name: "ISM Manufacturing PMI — Chỉ số PMI sản xuất",
        unit: "Index, 50 = không đổi",
        freq: "Hàng tháng (ngày 1 mỗi tháng)",
        source: "Institute for Supply Management",
        what: "Khảo sát purchasing managers ngành sản xuất về orders, production, employment, deliveries, inventories.",
        high_means: "Trên 50 = expansion. Tốt cho Industrials, Materials, Energy.",
        low_means: "Dưới 50 = contraction. Cyclicals chịu áp lực, defensive outperform.",
        why: "Là một trong những leading indicator được trade nhiều nhất. Component 'New Orders' đặc biệt quan trọng.",
        watch: "Dưới 45 = recession territory. Dưới 50 kéo dài 6+ tháng = manufacturing recession (có thể không lan ra full economy).",
      },
    },
    {
      match: /ism (non[- ]?manufacturing|services|service)/i,
      info: {
        name: "ISM Services PMI — Chỉ số PMI dịch vụ",
        unit: "Index, 50 = không đổi",
        freq: "Hàng tháng",
        source: "ISM",
        what: "PMI cho khu vực dịch vụ (chiếm ~80% kinh tế Mỹ).",
        high_means: "Dịch vụ mở rộng → tốt cho Discretionary, Communications, Financials.",
        low_means: "Dịch vụ co lại → toàn bộ kinh tế Mỹ cảnh báo.",
        why: "Quan trọng HƠN Manufacturing PMI vì dịch vụ chi phối GDP Mỹ. Tuy nhiên ít volatile hơn.",
        watch: "Dưới 50 hiếm gặp ngoài recession. Component 'Prices Paid' là chỉ báo lạm phát dịch vụ.",
      },
    },
    {
      match: /retail inventories/i,
      info: {
        name: "Retail Inventories — Tồn kho bán lẻ",
        unit: "% MoM",
        freq: "Hàng tháng",
        source: "Census Bureau",
        what: "Tồn kho hàng hoá tại các nhà bán lẻ.",
        high_means: "Có thể có 2 nghĩa: doanh nghiệp tự tin về cầu (tốt) HOẶC ế hàng (xấu).",
        low_means: "Thiếu hàng (cầu vượt cung — tốt) HOẶC cẩn trọng (xấu).",
        why: "Đi đôi với Retail Sales để tính inventory-to-sales ratio. Ratio cao = ế.",
        watch: "Khi tồn kho tăng + sales giảm = báo động cho margin.",
      },
    },
    {
      match: /\btrade balance\b/i,
      info: {
        name: "Trade Balance — Cán cân thương mại",
        unit: "Tỷ USD",
        freq: "Hàng tháng",
        source: "Census + BEA",
        what: "Xuất khẩu trừ nhập khẩu. Mỹ thường âm (deficit).",
        high_means: "Deficit thu hẹp (gần 0 hoặc dương) → đóng góp tích cực vào GDP. USD có thể yếu hơn (xuất khẩu mạnh = sản xuất nội địa khoẻ).",
        low_means: "Deficit mở rộng → trừ vào GDP. USD mạnh thường gây deficit lớn hơn.",
        why: "Là 'X-M' trong công thức GDP. Cũng phản ánh sức cạnh tranh của doanh nghiệp Mỹ vs nước ngoài.",
        watch: "Quan trọng cho USD: deficit lớn → áp lực USD yếu (long-term). Ngược lại với expectation ngắn hạn.",
      },
    },
    {
      match: /chicago pmi/i,
      info: {
        name: "Chicago PMI — PMI Chicago",
        unit: "Index",
        freq: "Hàng tháng",
        source: "ISM-Chicago",
        what: "PMI khu vực Chicago, được công bố 1 ngày trước ISM Manufacturing → leading proxy.",
        high_means: "Trên 50 = expansion. Báo hiệu ISM Manufacturing tốt.",
        low_means: "Dưới 50 = contraction.",
        why: "Trader dùng Chicago PMI để position cho ISM ngày hôm sau.",
        watch: "Volatile. Tốt cho short-term trades.",
      },
    },
    {
      match: /philadelphia fed|empire state/i,
      info: {
        name: "Regional Fed Manufacturing Survey — Khảo sát sản xuất khu vực",
        unit: "Diffusion index",
        freq: "Hàng tháng",
        source: "Federal Reserve Banks",
        what: "Khảo sát của Fed regional (Philly, NY, Richmond, Dallas, Kansas) về sản xuất khu vực.",
        high_means: "Manufacturing khu vực mở rộng.",
        low_means: "Co lại.",
        why: "Mỗi báo cáo public ở thời điểm khác nhau trong tháng, cùng nhau cho bức tranh manufacturing trước khi ISM ra.",
        watch: "Component 'New Orders' và 'Prices Paid' quan trọng nhất.",
      },
    },
  ],
};
